from __future__ import annotations

import json

from openai import OpenAI
from sqlalchemy import desc, or_, select
from sqlalchemy.orm import Session

from app.config import settings
from app.models import Anomaly, DuplicateRelationship, Project, RiskAssessment


SYSTEM_INSTRUCTIONS = """You are an investigation assistant for MPLADS monitoring officers.
Answer only from the supplied project evidence. Separate facts from recommended checks. Do not allege fraud,
misuse, or wrongdoing; describe risk indicators and verification steps. Keep the answer under 180 words and
refer to evidence identifiers in square brackets."""


def collect_evidence(session: Session, project: Project) -> list[dict[str, str]]:
    evidence: list[dict[str, str]] = [
        {
            "id": project.id,
            "type": "project",
            "label": f"Project record: {project.title}; utilization {project.utilization}%; physical progress {project.progress}%; risk {project.risk_score}/100.",
        }
    ]
    anomalies = list(
        session.scalars(
            select(Anomaly).where(Anomaly.project_id == project.id, Anomaly.status == "open").order_by(Anomaly.score.desc())
        )
    )
    for anomaly in anomalies[:5]:
        evidence.append({"id": anomaly.id, "type": "anomaly", "label": f"{anomaly.type}: {anomaly.explanation}"})

    assessment = session.scalar(
        select(RiskAssessment).where(RiskAssessment.project_id == project.id).order_by(desc(RiskAssessment.generated_at)).limit(1)
    )
    if assessment:
        evidence.append(
            {
                "id": f"risk-{assessment.id}",
                "type": "risk_assessment",
                "label": f"Explainable risk assessment {assessment.score}/100 generated by {assessment.model_version}.",
            }
        )

    duplicates = list(
        session.scalars(
            select(DuplicateRelationship)
            .where(
                or_(
                    DuplicateRelationship.project_a_id == project.id,
                    DuplicateRelationship.project_b_id == project.id,
                )
            )
            .order_by(DuplicateRelationship.similarity_score.desc())
        )
    )
    for relationship in duplicates[:3]:
        linked_id = relationship.project_b_id if relationship.project_a_id == project.id else relationship.project_a_id
        evidence.append(
            {
                "id": f"duplicate-{relationship.id}",
                "type": "duplicate_relationship",
                "label": f"Candidate linked to {linked_id}: {relationship.similarity_score}% similarity, {relationship.distance_km} km apart; {', '.join(relationship.reasons)}.",
            }
        )
    return evidence


def mock_answer(project: Project, question: str, evidence: list[dict[str, str]]) -> str:
    top_evidence = ", ".join(f"[{item['id']}]" for item in evidence[:3])
    question_lower = question.lower()
    if "duplicate" in question_lower:
        action = "Compare linked sanction orders, exact work boundaries, BOQ line items, implementing agency records, and geo-tagged evidence before deciding whether the works overlap."
    elif "cost" in question_lower or "financial" in question_lower or "fund" in question_lower:
        action = "Reconcile fund releases and invoices against certified physical progress, then inspect the largest BOQ variances before authorising another tranche."
    elif "delay" in question_lower or "timeline" in question_lower:
        action = "Verify the current milestone, remaining quantities, contractor recovery plan, and the latest inspection date before revising the completion forecast."
    else:
        action = "Start with the latest inspection evidence, fund-release vouchers, BOQ variances, and any linked-project records. Record each verification outcome in the audit trail."
    return f"{project.title} currently carries a {project.risk_score}/100 risk score. {action} Supporting records: {top_evidence}. These are risk indicators for review, not a finding of misuse."


def answer_question(session: Session, project: Project, question: str) -> tuple[str, list[dict[str, str]], str]:
    evidence = collect_evidence(session, project)
    if not settings.openai_api_key:
        return mock_answer(project, question, evidence), evidence, "rules-based-demo"

    client = OpenAI(api_key=settings.openai_api_key)
    response = client.responses.create(
        model=settings.openai_model,
        instructions=SYSTEM_INSTRUCTIONS,
        input=f"Officer question: {question}\n\nEvidence:\n{json.dumps(evidence, ensure_ascii=True)}",
        store=False,
        max_output_tokens=500,
    )
    return response.output_text, evidence, "openai-responses"

